name: Publish Fide Graph

on:
  push:
    tags:
      - "fide-graph/v*"

permissions:
  contents: write
  id-token: write
  deployments: write

jobs:
  publish-fide-graph:
    permissions:
      contents: write
      id-token: write
      deployments: write
    uses: ChrisLally/lally-workflows/.github/workflows/release-publish.yml@2fdeceddf40d5c7148e782ad94136115941d57a1
    with:
      tag_prefix: "fide-graph/v"
      install_working_directory: "packages/graph"
      package_dir: "packages/graph"
      deployment_environment: "Preview - fide-graph"
